name: world_time_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/usa.png
    - assets/south_korea.png
    - assets/egypt.png
    - assets/germany.png
    - assets/greece.png
    - assets/indonesia.png
    - assets/kenya.png
    - assets/uk.png
    - assets/india.png
    - assets/day.png
    - assets/night.png
